kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: nl-niveus-testing
  labels:
    app: mysql
    version: "1.0"
    environment: testing
spec:
  selector:
    app: mysql
    version: "1.0"
    environment: testing
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None